version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "jaf-userQuiz-py"
s3_bucket = "jvb-code"
s3_prefix = "SAM/jaf-userQuiz-py"
region = "ap-southeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
# parameter_overrides = ""
image_repositories = []
